### PR TITLE
Derive generic instances for Data.Date.Date and all types in Data.Time

### PR DESCRIPTION
**Pull request by wereHamster**

### CODE REVIEW

**Comment by garyb** [comment]
I don't think we can make a valid generic instance for this as it is a native type. That was @paf31's assertion in #19 at least.

**Comment by wereHamster** [comment]
I'm not representing a `Date` as a string but as a product with one constructor, and the millisecond value of the date object. I believe that's what derive would do if Date were a newtype around Millisecond.

Actually, why not make `Date` as a newtype around `Millisecond` instead of carrying around the native `JSDate`? If that were the case then we could automatically derive Generic! What would be the downsides?

**Comment by garyb** [comment]
That sounds like a good idea to me! It gets rid of the potential mutability of the date value too then :+1: 

We'd also need to keep a time offset with it too I think perhaps? That's good too though, as currently the timezone/offset support is Not Good.

**Comment by wereHamster** [comment]
FYI, I'm not using this module anymore (we switched away from PureScript, unfortunately). So if somebody wants to take over this pull request feel free to.

**Comment by FrigoEU** [comment]
@garyb what offset/timezone support do you think would be most beneficial? Is it the plan here to incorporate this whole body of (notoriously tricky) offset/timezone logic like a library like moment.js does?

Would it be a possibility to merge this PR as it is now and hold off on the move to a newtype around Milliseconds + timezone/offset? Or do you think that's a bad idea?

@wereHamster Am I correct in assuming that this PR is pretty complete as is, apart from the possible migration to a newtype around milliseconds + timezone/offset for the Date type?

**Comment by wereHamster** [comment]
@FrigoEU I think it's complete and can be merged. It certainly doesn't break any existing code and generic instance for `Date` is sound IMO.

**Comment by FrigoEU** [comment]
I did notice that there's some Generic Instances missing for Year, DateOfMonth, etc. I could do that work, but tbh I have no idea how to take over a PR :).

I agree with the current Generic instance for Date being sound.

**Comment by wereHamster** [comment]
@FrigoEU I think the best way is if I close this one and you open a new one.

**Comment by FrigoEU** [comment]
Okido, will do.

**Pull request closed without merging**
