### PR TITLE
Added Generic instance for Date

### PR DESCRIPTION
**Pull request by eskimor**
+ added two toString functions

### CODE REVIEW

**Comment by eskimor** [comment]
Oops - there is already a similar PR. Nevertheless - leaving it open as the instance is different.

**Comment by paf31** [comment]
`Date` is not `Generic` since it's not a sum of products.

**Comment by garyb** [comment]
There's been some previous discussion on this, #22. I want to change the representation to just hold the millis, and that way we avoid any weirdness and makes a proper generic instance possible.

**Comment by eskimor** [comment]
You guys are really fast. :-)

@paf31 : Would it make sense to add something like 

```purescript
SigNative String
SNative String
```
to `GenericSignature` / `GenericSpine` ? So we can represent native types?

Use case is for example generic JSON serialization/deserialization. As it currently fails completely if there is a single data type in the chain that has no Generic instance.

The above for JSDate would look something like

```purescript
SigNative "JSDate"
SNative "2016-03-24T17:02:50.848060000000Z"
```
Similar instances could be written for all native types which have some string representation.

**Pull request closed without merging**
