### PR TITLE
Add helpers to go from Instants to a duration

### LINKED ISSUE #98: Add a convenient way to get the `Millisecond`s between two `Instant`s
This is a use case I have often when timing things.
I would like to avoid running `unInstant` in application code. 

Maybe like this:

```purescript
-- | Get the amount of milliseconds between the first and second Instant
-- | for example:
-- | ```
-- | do
-- |   start <- Instant.now
-- |   aLongRunningEffect
-- |   end <- Instant.now
-- |   let duration = Instant.delta end start
-- |   log ("A long running effect took " <> show duration)
-- | ```
delta ∷ Instant → Instant → Milliseconds
delta i1 i2 = (unInstant i1) <> negateDuration (unInstant i2)
```

### PR DESCRIPTION
**Pull request by i-am-the-slime**
**Description of the change**

Fixes #98 
---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me! Do we like the name `duration` over `delta`? I know I was the one to suggest it, but I wonder if it's weird now since sometimes the result is going to be negative. I guess the library already promotes the idea of negative durations since the duration types don't have any restriction on that, but even still... thoughts?

**Comment by i-am-the-slime** [comment]
@garyb I like duration much better. I wouldn't mind `durationDelta` either.

**Review by JordanMartinez — APPROVED** [review]
I vote `durationDelta`

**Review by garyb — APPROVED** [review]

**Comment by garyb** [comment]
Thanks, sorry about the wait!

**Comment by f-f** [comment]
Is this an equivalent implementation? (found it in the assorted datetime code I carry around my projects)

```purescript
import Data.DateTime as DateTime
import Data.DateTime.Instant as Instant
import Data.Time.Duration as Duration

diffInstant :: forall a. Duration.Duration a => Instant -> Instant -> a
diffInstant a b = DateTime.diff (Instant.toDateTime a) (Instant.toDateTime b)
```

**Pull request merged**
