### PR TITLE
Add function for printing as ISO 8601 string

### PR DESCRIPTION
**Pull request by parsonsmatt**

### CODE REVIEW

**Comment by chrisdotcode** [comment]
+1 on this.

**Comment by chrisdotcode** [comment]
@parsonsmatt You actually forgot to export the function in your code.

**Comment by cdepillabout** [comment]
+1 on this from me too.

Although, it might make more sense to either call this `toStringStrict`, or rename `fromStringStrict` to `fromISOString`.  That way the from/to functions would have similar naming.

**Comment by garyb** [comment]
Perhaps just `toString`? `fromString` would parse this format as well, it's just that `fromStringStrict` will reject anything that is not exactly formatted this way.

**Comment by chrisdotcode** [comment]
IMO, I'm a fan of `fromISOString`, as it matches the current convention, but I'm really impartial; I care more about having this functionality in upstream than what it's called :)

**Comment by FrigoEU** [comment]
Would also like to see this get merged. Made a PR myself before I saw this... I actually also had it named toStringStrict, to match fromStringStrict.

**Comment by jonsterling** [comment]
I like having `ISO` in the name, since it is part of the correctness conditions of function that it adhere to the ISO 8601 format, but I don't really care... Would be great if we could get this merged and released though!

**Comment by garyb** [comment]
Thanks @parsonsmatt, sorry this one got left for so long!

**Comment by parsonsmatt** [comment]
No worries! Thanks for merging it in :smile:

**Pull request merged**
